// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supervisor.proto

package supervisor

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	HasErr               bool     `protobuf:"varint,1,opt,name=hasErr,proto3" json:"hasErr,omitempty"`
	ErrInfo              string   `protobuf:"bytes,2,opt,name=errInfo,proto3" json:"errInfo,omitempty"`
	TenantID             string   `protobuf:"bytes,3,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetHasErr() bool {
	if m != nil {
		return m.HasErr
	}
	return false
}

func (m *Result) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *Result) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

type AssignRequest struct {
	TenantID             string   `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	TidbStatusAddr       string   `protobuf:"bytes,2,opt,name=tidbStatusAddr,proto3" json:"tidbStatusAddr,omitempty"`
	PdAddr               string   `protobuf:"bytes,3,opt,name=pdAddr,proto3" json:"pdAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignRequest) Reset()         { *m = AssignRequest{} }
func (m *AssignRequest) String() string { return proto.CompactTextString(m) }
func (*AssignRequest) ProtoMessage()    {}
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{1}
}

func (m *AssignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignRequest.Unmarshal(m, b)
}
func (m *AssignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignRequest.Marshal(b, m, deterministic)
}
func (m *AssignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignRequest.Merge(m, src)
}
func (m *AssignRequest) XXX_Size() int {
	return xxx_messageInfo_AssignRequest.Size(m)
}
func (m *AssignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AssignRequest proto.InternalMessageInfo

func (m *AssignRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *AssignRequest) GetTidbStatusAddr() string {
	if m != nil {
		return m.TidbStatusAddr
	}
	return ""
}

func (m *AssignRequest) GetPdAddr() string {
	if m != nil {
		return m.PdAddr
	}
	return ""
}

type UnassignRequest struct {
	AssertTenantID       string   `protobuf:"bytes,1,opt,name=assertTenantID,proto3" json:"assertTenantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnassignRequest) Reset()         { *m = UnassignRequest{} }
func (m *UnassignRequest) String() string { return proto.CompactTextString(m) }
func (*UnassignRequest) ProtoMessage()    {}
func (*UnassignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{2}
}

func (m *UnassignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnassignRequest.Unmarshal(m, b)
}
func (m *UnassignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnassignRequest.Marshal(b, m, deterministic)
}
func (m *UnassignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnassignRequest.Merge(m, src)
}
func (m *UnassignRequest) XXX_Size() int {
	return xxx_messageInfo_UnassignRequest.Size(m)
}
func (m *UnassignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnassignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnassignRequest proto.InternalMessageInfo

func (m *UnassignRequest) GetAssertTenantID() string {
	if m != nil {
		return m.AssertTenantID
	}
	return ""
}

type GetTenantResponse struct {
	TenantID             string   `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTenantResponse) Reset()         { *m = GetTenantResponse{} }
func (m *GetTenantResponse) String() string { return proto.CompactTextString(m) }
func (*GetTenantResponse) ProtoMessage()    {}
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{3}
}

func (m *GetTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTenantResponse.Unmarshal(m, b)
}
func (m *GetTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTenantResponse.Marshal(b, m, deterministic)
}
func (m *GetTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTenantResponse.Merge(m, src)
}
func (m *GetTenantResponse) XXX_Size() int {
	return xxx_messageInfo_GetTenantResponse.Size(m)
}
func (m *GetTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTenantResponse proto.InternalMessageInfo

func (m *GetTenantResponse) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "supervisor.Result")
	proto.RegisterType((*AssignRequest)(nil), "supervisor.AssignRequest")
	proto.RegisterType((*UnassignRequest)(nil), "supervisor.UnassignRequest")
	proto.RegisterType((*GetTenantResponse)(nil), "supervisor.GetTenantResponse")
}

func init() { proto.RegisterFile("supervisor.proto", fileDescriptor_b8b9452d77b1c7d2) }

var fileDescriptor_b8b9452d77b1c7d2 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x9a, 0x54, 0x9c, 0x28, 0xe0, 0x1e, 0x48, 0x2d, 0x31, 0x21, 0x3d, 0x10, 0x4e, 0xdb,
	0x44, 0xe3, 0xc1, 0x93, 0x01, 0x24, 0x84, 0x78, 0x21, 0x45, 0x3d, 0x78, 0x2b, 0x76, 0x58, 0x1b,
	0xcb, 0x6e, 0xdd, 0xdd, 0x1a, 0xfd, 0xad, 0xfe, 0x19, 0xd3, 0x2f, 0x68, 0x31, 0x7a, 0xdb, 0x37,
	0x33, 0x6f, 0xde, 0xbc, 0x7d, 0xd0, 0x51, 0x49, 0x8c, 0xf2, 0x23, 0x54, 0x42, 0xd2, 0x58, 0x0a,
	0x2d, 0x08, 0xec, 0x2a, 0x76, 0x8f, 0x09, 0xc1, 0x22, 0x74, 0xb3, 0xce, 0x2a, 0x59, 0xbb, 0xb8,
	0x89, 0xf5, 0x57, 0x3e, 0xe8, 0x3c, 0x81, 0xe9, 0xa1, 0x4a, 0x22, 0x4d, 0xba, 0x60, 0xbe, 0xfa,
	0x6a, 0x2a, 0xa5, 0x65, 0xf4, 0x8d, 0x61, 0xd3, 0x2b, 0x10, 0xb1, 0xe0, 0x08, 0xa5, 0x9c, 0xf3,
	0xb5, 0xb0, 0x0e, 0xfa, 0xc6, 0xf0, 0xd8, 0x2b, 0x21, 0xb1, 0xa1, 0xa9, 0x91, 0xfb, 0x5c, 0xcf,
	0xef, 0xac, 0xc3, 0xac, 0xb5, 0xc5, 0xce, 0x1b, 0x9c, 0x8e, 0x94, 0x0a, 0x19, 0xf7, 0xf0, 0x3d,
	0x41, 0xa5, 0x6b, 0xc3, 0x46, 0x7d, 0x98, 0x0c, 0xa0, 0xa5, 0xc3, 0x60, 0xb5, 0xd4, 0xbe, 0x4e,
	0xd4, 0x28, 0x08, 0x64, 0xa1, 0xb4, 0x57, 0x4d, 0x4f, 0x8c, 0x83, 0xac, 0x9f, 0xcb, 0x15, 0xc8,
	0xb9, 0x81, 0xf6, 0x23, 0xf7, 0x6b, 0x72, 0x03, 0x68, 0xf9, 0x4a, 0xa1, 0xd4, 0x0f, 0x75, 0xd1,
	0xbd, 0xaa, 0xe3, 0xc2, 0xd9, 0x0c, 0x0b, 0xe8, 0xa1, 0x8a, 0x05, 0x57, 0xf8, 0xdf, 0xad, 0x97,
	0xdf, 0x06, 0x98, 0xb9, 0x33, 0x72, 0x0b, 0x27, 0xf9, 0x2b, 0xa7, 0x93, 0x73, 0x5a, 0xc9, 0xa1,
	0xe6, 0xde, 0x26, 0xd5, 0x56, 0xfe, 0xe1, 0x4e, 0x83, 0x4c, 0xa0, 0x55, 0xde, 0x5d, 0xac, 0xe8,
	0x55, 0xe7, 0xf6, 0x3c, 0xfd, 0xb1, 0xe4, 0x1e, 0x3a, 0x33, 0xd4, 0x93, 0x44, 0x4a, 0xe4, 0x85,
	0x11, 0xd2, 0xa5, 0x79, 0xe6, 0xb4, 0xcc, 0x9c, 0x4e, 0xd3, 0xcc, 0xed, 0x8b, 0xea, 0x86, 0x5f,
	0xbe, 0x9d, 0xc6, 0x98, 0x41, 0x2f, 0x14, 0x94, 0xc9, 0xf8, 0x85, 0xe2, 0xa7, 0xbf, 0x89, 0x23,
	0x54, 0x15, 0xca, 0xb8, 0xbd, 0xdc, 0xbe, 0x17, 0xe9, 0xe6, 0x85, 0xf1, 0x7c, 0x5d, 0x28, 0x31,
	0x11, 0xf9, 0x9c, 0x51, 0x21, 0x99, 0x9b, 0xd2, 0xdd, 0x92, 0xee, 0xee, 0xe8, 0x95, 0xe7, 0xca,
	0xcc, 0x2e, 0xbb, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x83, 0xb0, 0xd7, 0xbb, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AssignClient is the client API for Assign service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AssignClient interface {
	AssignTenant(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*Result, error)
	UnassignTenant(ctx context.Context, in *UnassignRequest, opts ...grpc.CallOption) (*Result, error)
	GetCurrentTenant(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTenantResponse, error)
}

type assignClient struct {
	cc *grpc.ClientConn
}

func NewAssignClient(cc *grpc.ClientConn) AssignClient {
	return &assignClient{cc}
}

func (c *assignClient) AssignTenant(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/supervisor.Assign/AssignTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assignClient) UnassignTenant(ctx context.Context, in *UnassignRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/supervisor.Assign/UnassignTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assignClient) GetCurrentTenant(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, "/supervisor.Assign/GetCurrentTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssignServer is the server API for Assign service.
type AssignServer interface {
	AssignTenant(context.Context, *AssignRequest) (*Result, error)
	UnassignTenant(context.Context, *UnassignRequest) (*Result, error)
	GetCurrentTenant(context.Context, *empty.Empty) (*GetTenantResponse, error)
}

func RegisterAssignServer(s *grpc.Server, srv AssignServer) {
	s.RegisterService(&_Assign_serviceDesc, srv)
}

func _Assign_AssignTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignServer).AssignTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.Assign/AssignTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignServer).AssignTenant(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Assign_UnassignTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignServer).UnassignTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.Assign/UnassignTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignServer).UnassignTenant(ctx, req.(*UnassignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Assign_GetCurrentTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignServer).GetCurrentTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.Assign/GetCurrentTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignServer).GetCurrentTenant(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Assign_serviceDesc = grpc.ServiceDesc{
	ServiceName: "supervisor.Assign",
	HandlerType: (*AssignServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignTenant",
			Handler:    _Assign_AssignTenant_Handler,
		},
		{
			MethodName: "UnassignTenant",
			Handler:    _Assign_UnassignTenant_Handler,
		},
		{
			MethodName: "GetCurrentTenant",
			Handler:    _Assign_GetCurrentTenant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supervisor.proto",
}
